version: '3.8'

services:
  db:
    image: postgres:14
    container_name: go_shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654123
      POSTGRES_DB: go_shop
      POSTGRES_LISTEN_ADDRESSES: '*'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: