services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=987654123
      - DB_NAME=go_shop
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: postgres:14
    container_name: go_shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654123
      POSTGRES_DB: go_shop
      POSTGRES_LISTEN_ADDRESSES: '*'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: